### ISSUE TITLE
Process crashes immediately

### ISSUE THREAD

**Issue by TenTakano** [jeffgrunewald/glock#5]
Hi,

I've tried the first example in README.md, however, the following message appears after established once. Do I need some dependencies or the library has some bugs?

```
iex(1)> res = Sample.start_link(host: "ws://echo.websocket.org", path: "/")
{:ok, #PID<0.306.0>}
iex(2)> 
21:06:34.990 [info]  Terminating client process with reason : {{:badmatch, {:error, {:shutdown, :nxdomain}}}, [{Sample, :handle_continue, 2, [file: 'lib/glock/socket.ex', line: 99]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 680]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 431]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}
 
21:06:35.001 [error] GenServer :"ws:__echo.websocket.org_" terminating
** (ArgumentError) argument error
    :erlang.demonitor(nil)
    (sample 0.1.0) lib/glock/socket.ex:207: Sample.terminate/2
    (stdlib 3.13.2) gen_server.erl:718: :gen_server.try_terminate/3
    (stdlib 3.13.2) gen_server.erl:903: :gen_server.terminate/10
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :connect}
State: %Glock.Conn{client: nil, connect_opts: %{connect_timeout: 60000, retry: 10, retry_timeout: 300, transport: :tcp}, handler_init_args: %{}, headers: [], host: 'ws://echo.websocket.org', monitor: nil, path: '/', port: 80, stream: nil, stream_state: nil, ws_opts: %{closing_timeout: 15000, compress: false, keepalive: 5000}}
** (EXIT from #PID<0.304.0>) shell process exited with reason: an exception was raised:
    ** (ArgumentError) argument error
        :erlang.demonitor(nil)
        (sample 0.1.0) lib/glock/socket.ex:207: Sample.terminate/2
        (stdlib 3.13.2) gen_server.erl:718: :gen_server.try_terminate/3
        (stdlib 3.13.2) gen_server.erl:903: :gen_server.terminate/10
        (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3j
```

Here is my environment

- elixir 1.10.4
- erlang 23.1.5
- Ubuntu 20.04 LTS

I've tried also the following, but I got the same error messages.
- elixir 1.11.2, erlang 23.1.5
- elixir 1.9.4, erlang 20.3.8.26

**Comment by jeffgrunewald** [comment]
Hey, thanks for the question and trying out the library; once we've gotten this squared away I hope you'll find it helpful.

Just tested this out with the `websocket.org` service and I'm going to blame my documentation in the example as not being representative enough (since I'm only showing an example assuming a local websocket server like a socket.io or cowboy-based websocket server.

The actual example configuration you'll want with a non-local socket server would be `res = Sample.start_link(host: "echo.websocket.org", path: "/")` so you'd drop the `ws://` prefix from the connection. Since Gun is not specific to websockets if you're wanting to use TLS for your connection you'd pass that as part of the connection options instead of as part of the URL.

Hope that helps; pushing out a documentation change to make this more clear with some minor dependency updates since the original release.

**Comment by TenTakano** [comment]
Thank you for replying and updating.
I've tried a bit according to your comment again. Then, I could make connection without any message.

But I found one more mistake on the first Example of README.md.
So I submitted a PR(#8 )
Please check it. Thanks!

**Comment by jeffgrunewald** [comment]
Thanks so much for the fix; merged!
